services:
  app:
    container_name: flaskapp
    build: .
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    links:
      - db
      - elasticsearch
  db:
    image: mongo
    container_name: mongodb
    restart: always
    hostname: test_mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017
  elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
      container_name: elasticsearch
      restart: always
      environment:
        - node.name=test_elasticsearch
        - discovery.type=single-node
        - xpack.security.enabled=false
      ports:
        - 9200:9200
        - 9300:9300